[package]
name = "shortly-new"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.5.4" 
serde_json = "1.0.137"
serde = { version = "1.0.217", features = ["derive"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }